# Generated by Django 4.2.2 on 2023-07-04 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_historyproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historyproduct',
            name='user_id',
        ),
    ]
