# Generated by Django 4.2.2 on 2023-07-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_historyproduct_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='HistoryProduct',
        ),
    ]
